### ISSUE TITLE
 Unexpected token ...

### ISSUE THREAD

**Issue by koushikdutta** [isaacs/node-mkdirp#10]
\node_modules\grunt\node_modules\mkdirp\lib\opts-arg.js:7
    opts = { mode: 0o777 & (~process.umask()), fs, ...opts }
                                                   ^^^

SyntaxError: Unexpected token ...
  at createScript (vm.js:56:10)
  at Object.runInThisContext (vm.js:97:10)
  at Module._compile (module.js:549:28)
  at Object.Module._extensions..js (module.js:586:10)
  at Module.load (D:\Works\Mediakind\WMC\Git\WMC_Master\node_modules\coffeescript\lib\coffee-script\register.js:45:36)   at tryModuleLoad (module.js:453:12)
  at Function.Module._load (module.js:445:3)
  at Module.require (module.js:504:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (D:\Works\Mediakind\WMC\Git\WMC_Master\node_modules\grunt\node_modules\mkdirp\index.js:1:79)     at Module._compile (module.js:577:32)
  at Object.Module._extensions..js (module.js:586:10)
  at Module.load (D:\Works\Mediakind\WMC\Git\WMC_Master\node_modules\coffeescript\lib\coffee-script\register.js:45:36)   at tryModuleLoad (module.js:453:12)
  at Function.Module._load (module.js:445:3)
  at Module.require (module.js:504:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (D:\Works\Mediakind\WMC\Git\WMC_Master\node_modules\grunt\lib\grunt\file.js:20:31)
  at Module._compile (module.js:577:32)
  at Object.Module._extensions..js (module.js:586:10)
  at Module.load (D:\Works\Mediakind\WMC\Git\WMC_Master\node_modules\coffeescript\lib\coffee-script\register.js:45:36)   at tryModuleLoad (module.js:453:12)
  at Function.Module._load (module.js:445:3)
  at Module.require (module.js:504:17)
  at require (internal/module.js:20:19)
  at gRequire (D:\Works\Mediakind\WMC\Git\WMC_Master\node_modules\grunt\lib\grunt.js:14:24)
  at Object.<anonymous> (D:\Works\Mediakind\WMC\Git\WMC_Master\node_modules\grunt\lib\grunt.js:28:1)
  at Module._compile (module.js:577:32)
  at Object.Module._extensions..js (module.js:586:10)
  at Module.load (module.js:494:32)
  at tryModuleLoad (module.js:453:12)
  at Function.Module._load (module.js:445:3)
  at Module.require (module.js:504:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (D:\Works\Mediakind\WMC\Git\WMC_Master\node_modules\grunt-cli\bin\grunt:45:1)
  at Module._compile (module.js:577:32)
  at Object.Module._extensions..js (module.js:586:10)
  at Module.load (module.js:494:32)
  at tryModuleLoad (module.js:453:12)
  at Function.Module._load (module.js:445:3)
  at Module.runMain (module.js:611:10)
  at run (bootstrap_node.js:387:7)
  at startup (bootstrap_node.js:153:9)
  at bootstrap_node.js:500:3

**Comment by LinusU** [comment]
`mkdirp` only supports Node.js 10.x and above 🚀 

Please note that all older versions of Node.js are in the end-of-life state and are no longer receiving security updates. I would strongly recommend you to upgrade to the latest LTS versions.

**Comment by hubgit** [comment]
It might be a good idea to remove "This module works on node v8" from the documentation, unless there's a workaround.

https://github.com/isaacs/node-mkdirp#platform-support

**Comment by DanielRuf** [comment]
You have to check which dependency uses the wrong version. In my case it was grunt.

**Comment by lavish-tyagi-rsi** [comment]
Hello,

Which version is compatible for node 7..

Please revert ASAP

**Comment by DanielRuf** [comment]
> Please revert ASAP

Not needed, use mkdirp 0.5.4:
https://github.com/isaacs/node-mkdirp/releases/tag/v0.5.4

**Comment by isaacs** [comment]
Only v10 and above is supported by mkdirp 1.x.  You may continue to use the deprecated/unsupported 0.x version if you are running on EOL node versions, but I recommend updating your node version as soon as possible to a supported version that will continue to get security updates.
